version: '3.8'

services:
  app:
    image: jossoft34/devops-person-info:latest
    container_name: devops-person-info
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/swe304
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=swe304
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: